@RiotStore.API_HostAddress = https://localhost:7034

### Get all products
GET {{RiotStore.API_HostAddress}}/api/products
Accept: application/json

### Get product by ID
GET {{RiotStore.API_HostAddress}}/api/products/1
Accept: application/json