<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RiotStore.Consumer-782e6944-36a6-4aaf-9998-fb348546f8f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiotStore.Infrastructure\RiotStore.Infrastructure.csproj" />
    <ProjectReference Include="..\RiotStore.Shared\RiotStore.Shared.csproj" />
  </ItemGroup>
</Project>
